name: Production deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: our echo
        run: echo ${{ secrets.HEROKU_API_KEY }}
      - name: Add api remote origin
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/connectfaf.git
      - name: Deploy api to Heroku
        run: |
          git subtree push --prefix backend heroku master
